import {v4} from 'uuid'

const {parse, build} = globalThis.plist;



export interface Config {
	name?: string
	url?: string
	icon?: string
	config_name?: string
        config_author?: string
}

export interface MCPlist {
        [k: string]: unknown
}

export function generateConfig(config: Config): string {
        let payload_uuid = v4().toUpperCase()
        let app_uuid = v4().toUpperCase()
        let mobileconfig = `<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
                <key>PayloadContent</key>
                <array>
                        <dict>
                                <key>FullScreen</key>
                                <true/>
                                <key>Icon</key>
                                <data>${config.icon}</data>
                                <key>IsRemovable</key>
                                <true/>
                                <key>Label</key>
                                <string>${config.name}</string>
                                <key>PayloadDescription</key>
                                <string>Web app bundld into a config, generated by @S0n1c_Dev</string>
                                <key>PayloadDisplayName</key>
                                <string>${config.name}</string>
                                <key>PayloadIdentifier</key>
                                <string>com.apple.webClip.managed.${payload_uuid}</string>
                                <key>PayloadType</key>
                                <string>com.apple.webClip.managed</string>
                                <key>PayloadUUID</key>
                                <string>${payload_uuid}</string>
                                <key>PayloadVersion</key>
                                <integer>1</integer>
                                <key>Precomposed</key>
                                <true/>
                                <key>URL</key>
                                <string>${config.url}</string>
                        </dict>
                </array>
                <key>PayloadDescription</key>
                <string>This config was generated via WebClip Maker by @S0n1c_Dev.</string>
                <key>PayloadDisplayName</key>
                <string>${config.config_name}</string>
                <key>PayloadIdentifier</key>
                <string>ca.s0n1c.ios.webclip.${app_uuid}</string>
                <key>PayloadOrganization</key>
                <string>${config.config_author}</string>
                <key>PayloadRemovalDisallowed</key>
                <false/>
                <key>PayloadType</key>
                <string>Configuration</string>
                <key>PayloadUUID</key>
                <string>${app_uuid}</string>
                <key>PayloadVersion</key>
                <integer>1</integer>
        </dict>
        </plist>`
       
        return mobileconfig;
}
